Added proper argument handling to chroots-init along with verbosity options

diff --git a/chroots-init b/chroots-init
--- a/chroots-init
+++ b/chroots-init
@@ -1,8 +1,25 @@
 #!/bin/bash
 
 DISTRO=/var/chroot/hardy
-
 BIND_DIRS="dev tmp"
+VERBOSE=0
+
+
+function usage {
+
+NAME=`echo $1 | sed -e "s/\.\///g"`
+
+cat << EOF
+usage: $NAME COMMAND
+
+  Mount the necessary partitions to start the specified chroot.
+
+OPTIONS:
+    -h, --help    Show this message
+    -v, --verbose Verbose output
+EOF
+    exit 0;
+}
 
 if [ $UID != 0 ]; then
 	echo "Superuser permissions required. Aborting."
@@ -13,8 +30,52 @@ if [ "$1" != "" ]; then
 	DISTRO=$1;
 fi;
 
+OPTS="+vh"
+LONGOPTS="verbose,help"
+TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
+
+eval set -- "$TEMP"
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+while true; do
+	case "$1" in
+		--help|-h)
+			usage $0;
+			exit 0;
+			shift;
+			;;
+		--verbose|-v)
+			VERBOSE=1
+			shift;
+			;;
+		--)
+			shift;
+			break;
+			;;
+		*)
+			echo "Error parsing options";
+			exit 1;
+			;;
+	esac
+done;
+
+# Check input and select a chroot
+
+# Find the necessary mount points and verify
+
+
+# Mount
+
+if [ $VERBOSE != 0 ]; then
+	echo "Mount proc dir $DISTRO/proc"
+fi;
+
 mount -t proc none $DISTRO/proc
 
 for i in $BIND_DIRS; do
+	if [ $VERBOSE != 0 ]; then
+		echo "Binding $i to $DISTRO/$i"
+	fi;
 	mount -o bind /$i $DISTRO/$i
 done;
