Adder proper argument support to chroots-list

diff --git a/chroots-list b/chroots-list
--- a/chroots-list
+++ b/chroots-list
@@ -2,6 +2,9 @@
 
 CONF="$HOME/.chroots"
 
+CHECK=0
+CLEAN=0
+
 function usage {
 NAME=`echo $1 | sed -e "s/\.\///g"`
 
@@ -10,18 +13,50 @@ NAME=`echo $1 | sed -e "s/\.\///g"`
  Usage example: $NAME list
 
 OPTIONS:
-  -h, --help    Show this message
+  -h, --help           Show this message
+  -v, --verbose        Verbose mode
+  -c, --check          Check the validity of listed chroots
+  -C, --clean          Remove failed chroots
 EOF
 }
 
 # Begin program
 
-case "$1" in
-	--help|-h)
-		usage $0
-		exit 0
-		;;
-esac
+OPTS="vhcC"
+LONGOPTS="verbose,help,check,clean"
+
+TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
+
+eval set -- "$TEMP"
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+while true;  do
+	case "$1" in
+		--help|-h)
+			usage $0
+			exit 0
+			;;
+		--check|-c)
+			CHECK=1
+			echo "Checking valid chroots"
+			shift;
+			;;
+		--clean|-C)
+			CLEAN=1
+			echo "Removing any failed chroots"
+			shift;
+			;;
+		--)
+			shift;
+			break;
+			;;
+		*)
+			echo "Error parsing options";
+			exit 1;
+			;;
+	esac
+done;
 
 if [ ! -r $CONF ]; then
 	exit 0
