Fix invalid argument handling in chroots-init

diff --git a/chroots-init b/chroots-init
--- a/chroots-init
+++ b/chroots-init
@@ -26,9 +26,14 @@ OPTS="vh"
 LONGOPTS="verbose,help"
 TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
 
+if [ $? != 0 ]; then
+	echo "Invalid arguments";
+	usage $0;
+	exit 1 ;
+fi
+
 eval set -- "$TEMP"
 
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 while true; do
 	case "$1" in
