Add proper argument parsing and behavior skeleton

diff --git a/chroots-stop b/chroots-stop
--- a/chroots-stop
+++ b/chroots-stop
@@ -1,7 +1,78 @@
 #!/bin/bash
 
-DISTRO=/var/chroot/hardy
+CHROOTS=$HOME/.chroots
+CHRTARGET=/var/chroot/hardy
+CHRNAME=hardy
+VERBOSE=0
 
-sudo umount $DISTRO/proc
-sudo umount $DISTRO/dev
-sudo umount $DISTRO/tmp
+function usage {
+
+NAME=`echo $1 | sed -e "s/\.\///g"`
+
+	cat << EOF
+ $NAME [target] [OPTIONS]"
+ Usage example: $NAME hardy"
+
+  Unmount the specified chroot.
+
+OPTIONS:
+  -h, --help      Show this message
+  -v, --verbose   Verbose
+
+EOF
+exit 0
+}
+
+OPTS="+vh"
+LONGOPTS="verbose,help"
+TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
+
+eval set -- "$TEMP"
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+while true; do
+	case "$1" in
+		--help|-h)
+			usage $0;
+			exit 0;
+			shift;
+			;;
+		--verbose|-v)
+			VERBOSE=1
+			shift;
+			;;
+		--)
+			shift;
+			break;
+			;;
+		*)
+			echo "Error parsing options";
+			exit 1;
+			;;
+	esac
+done;
+
+if [ $UID != 0 ]; then
+	echo "Superuser permissions required. Aborting."
+	exit 1
+fi;
+
+# Determine chroot to use
+
+if [ "$1" != "" ]; then
+	CHRNAME=$1
+fi;
+
+# Validate chroot
+
+# Get CHRTARGET form CHRNAME
+
+# Try to unmount
+
+for i in "proc dev tmp"; do
+	if [ $VERBOSE == 1 ]; then
+		echo "Unmount $CHRTARGET/$I";
+	fi;
+	umount $CHRTARGET/$i
+done;
