Load functions from the global install

diff --git a/chroots-delete b/chroots-delete
--- a/chroots-delete
+++ b/chroots-delete
@@ -16,7 +16,19 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>
 #
 
-. chroots-functions
+if [ -r chroots-functions ]; then
+	echo "Running in development mode."
+	CHROOTSLIB=chroots-functions
+else
+	if [ -r /usr/lib/chroots-functions ]; then
+		CHROOTSLIB=/usr/lib/chroots-functions
+	else
+		echo "chroots library not found."
+		exit 1
+	fi;
+fi;
+
+. $CHROOTSLIB
 
 FORCE=0
 
diff --git a/chroots-init b/chroots-init
--- a/chroots-init
+++ b/chroots-init
@@ -16,9 +16,21 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>
 #
 
-BINDDIRS="dev tmp"
+if [ -r chroots-functions ]; then
+	echo "Running in development mode."
+	CHROOTSLIB=chroots-functions
+else
+	if [ -r /usr/lib/chroots-functions ]; then
+		CHROOTSLIB=/usr/lib/chroots-functions
+	else
+		echo "chroots library not found."
+		exit 1
+	fi;
+fi;
 
-. chroots-functions
+. $CHROOTSLIB
+
+BINDDIRS="dev tmp"
 
 function usage {
 
diff --git a/chroots-setup b/chroots-setup
--- a/chroots-setup
+++ b/chroots-setup
@@ -16,10 +16,22 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>
 #
 
+if [ -r chroots-functions ]; then
+	echo "Running in development mode."
+	CHROOTSLIB=chroots-functions
+else
+	if [ -r /usr/lib/chroots-functions ]; then
+		CHROOTSLIB=/usr/lib/chroots-functions
+	else
+		echo "chroots library not found."
+		exit 1
+	fi;
+fi;
+
+. $CHROOTSLIB
+
 MIRROR="http://archive.ubuntu.com/ubuntu"
 DEBOOTSTRAP=/usr/sbin/debootstrap
-
-. chroots-functions
 
 function usage {
 NAME=`echo $1 | sed -e "s/\.\///g"`
