Invalid arguments handling.

diff --git a/chroots-delete b/chroots-delete
--- a/chroots-delete
+++ b/chroots-delete
@@ -23,7 +23,12 @@ EOF
 OPTS="vhf"
 LONGOPTS="verbose,help,force"
 TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+if [ $? != 0 ]; then
+	echo "Invalid arguments";
+	usage $0;
+	exit 1;
+fi;
 
 eval set -- "$TEMP"
 
diff --git a/chroots-stop b/chroots-stop
--- a/chroots-stop
+++ b/chroots-stop
@@ -24,11 +24,17 @@ EOF
 
 OPTS="vhf"
 LONGOPTS="verbose,help,force"
+
 TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`
+
+if [ $? != 0 ] ; then
+	echo "Invalid arguments.";
+	usage $0;
+	exit 1;
+fi
 
 eval set -- "$TEMP"
 
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 while true; do
 	case "$1" in
