Added library mount checks and smart chroot detection

diff --git a/chroots-functions b/chroots-functions
--- a/chroots-functions
+++ b/chroots-functions
@@ -17,6 +17,16 @@ function chroots_version {
 	echo "$PROGNAME $PROGVERSION - Copyright (C) Alfredo Matos 2008"
 }
 
+function get_work_chroot {
+	if [ "$1" == "" ]; then
+        	get_default_chroot;
+	        echo "Using default chroot $DEFAULT_CHRNAME";
+        	_CHRNAME=$DEFAULT_CHRNAME;
+	else
+        	_CHRNAME=$1;
+	fi;
+}
+
 function get_default_chroot {
 	if [ -r /etc/lsb-release ]; then
 		. /etc/lsb-release
@@ -35,22 +45,71 @@ function chroots_get_chroot {
 	CFG=`grep "^$1 " $CHROOTS` 
 
 	if [ "$CFG" == "" ]; then
+		if [ $VERBOSE == 1 ]; then
+			echo "$1 does no exist in $CHROOTS"
+		fi;
 		return 1;
 	fi;
 
 	_CHRTARGET=`echo $CFG | cut -d " " -f 2`
 	_CHRUSER=`echo $CFG | cut -d " " -f 3`
 	_CHRNAME=$1
+
+	return 0;
+}
+
+function __chroots_check_mount {
+	DEV=$1
+	TARGET=$2
+
+	MOUNTOUTPUT=`mount | grep "^$DEV on $TARGET"`
+
+	if [ "$MOUNTOUTPUT" != "" ]; then
+		return 1;
+	fi;
+
+	return 0;
 }
 
 function chroots_check_mount {
+
 	chroots_get_chroot $1;
 
 	if [ $? != 0 ]; then
+		echo "Mount check failed because $1 does not exist"
 		return 2;
 	fi;
 
-	echo "Chekcing if $_CHRNAME is mounted..."
+	if [ $VERBOSE == 1 ]; then
+		echo "Checking if $_CHRNAME is mounted..."
+	fi;
+
+	__chroots_check_mount "none" "$_CHRTARGET/proc"
+	PROCMOUNT=$?
+
+	__chroots_check_mount "/dev" "$_CHRTARGET/dev"
+	DEVMOUNT=$?
+
+	__chroots_check_mount "/tmp" "$_CHRTARGET/tmp"
+	TMPMOUNT=$?
+
+	if [ $VERBOSE == 1 ]; then
+		if [ $PROCMOUNT == 0 ]; then
+			echo "$_CHRTARGET/proc is not mounted"
+		fi;
+
+		if [ $DEVMOUNT == 0 ]; then
+			echo "$_CHRTARGET/dev is not mounted"
+		fi;
+
+		if [ $TMPMOUNT == 0 ]; then
+			echo "$_CHRTARGET/tmp is not mounted"
+		fi;
+	fi;
+
+	if [[ $PROCMOUNT == 1 || $DEVMOUNT == 1 || $TMPMOUNT == 1 ]]; then
+		return 1;
+	fi;
 
 	return 0;
 }
